/* noms_en.c : noms anglais d'origine des objets et monstres, conserves
 * pour les recherches par nom (niveaux Lua, voeux, options). Genere. */

#include "hack.h"

const char *const en_obj_names[NUM_OBJECTS + 1] = {
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
    "strange object",
};

const char *const en_obj_descrs[NUM_OBJECTS + 1] = {
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
};

const char *const en_mon_names[NUMMONS + 1][NUM_MGENDERS] = {
    { (const char *) 0, (const char *) 0, "giant ant" },
    { (const char *) 0, (const char *) 0, "killer bee" },
    { (const char *) 0, (const char *) 0, "soldier ant" },
    { (const char *) 0, (const char *) 0, "fire ant" },
    { (const char *) 0, (const char *) 0, "giant beetle" },
    { (const char *) 0, (const char *) 0, "queen bee" },
    { (const char *) 0, (const char *) 0, "acid blob" },
    { (const char *) 0, (const char *) 0, "quivering blob" },
    { (const char *) 0, (const char *) 0, "gelatinous cube" },
    { (const char *) 0, (const char *) 0, "chickatrice" },
    { (const char *) 0, (const char *) 0, "cockatrice" },
    { (const char *) 0, (const char *) 0, "pyrolisk" },
    { (const char *) 0, (const char *) 0, "jackal" },
    { (const char *) 0, (const char *) 0, "fox" },
    { (const char *) 0, (const char *) 0, "coyote" },
    { (const char *) 0, (const char *) 0, "werejackal" },
    { (const char *) 0, (const char *) 0, "little dog" },
    { (const char *) 0, (const char *) 0, "dingo" },
    { (const char *) 0, (const char *) 0, "dog" },
    { (const char *) 0, (const char *) 0, "large dog" },
    { (const char *) 0, (const char *) 0, "wolf" },
    { (const char *) 0, (const char *) 0, "werewolf" },
    { (const char *) 0, (const char *) 0, "winter wolf cub" },
    { (const char *) 0, (const char *) 0, "warg" },
    { (const char *) 0, (const char *) 0, "winter wolf" },
    { (const char *) 0, (const char *) 0, "hell hound pup" },
    { (const char *) 0, (const char *) 0, "hell hound" },
    { (const char *) 0, (const char *) 0, "gas spore" },
    { (const char *) 0, (const char *) 0, "floating eye" },
    { (const char *) 0, (const char *) 0, "freezing sphere" },
    { (const char *) 0, (const char *) 0, "flaming sphere" },
    { (const char *) 0, (const char *) 0, "shocking sphere" },
    { (const char *) 0, (const char *) 0, "kitten" },
    { (const char *) 0, (const char *) 0, "housecat" },
    { (const char *) 0, (const char *) 0, "jaguar" },
    { (const char *) 0, (const char *) 0, "lynx" },
    { (const char *) 0, (const char *) 0, "panther" },
    { (const char *) 0, (const char *) 0, "large cat" },
    { (const char *) 0, (const char *) 0, "tiger" },
    { (const char *) 0, (const char *) 0, "displacer beast" },
    { (const char *) 0, (const char *) 0, "gremlin" },
    { (const char *) 0, (const char *) 0, "gargoyle" },
    { (const char *) 0, (const char *) 0, "winged gargoyle" },
    { (const char *) 0, (const char *) 0, "hobbit" },
    { (const char *) 0, (const char *) 0, "dwarf" },
    { (const char *) 0, (const char *) 0, "bugbear" },
    { "dwarf lord", "dwarf lady", "dwarf leader" },
    { "dwarf king", "dwarf queen", "dwarf ruler" },
    { (const char *) 0, (const char *) 0, "mind flayer" },
    { (const char *) 0, (const char *) 0, "master mind flayer" },
    { (const char *) 0, (const char *) 0, "manes" },
    { (const char *) 0, (const char *) 0, "homunculus" },
    { (const char *) 0, (const char *) 0, "imp" },
    { (const char *) 0, (const char *) 0, "lemure" },
    { (const char *) 0, (const char *) 0, "quasit" },
    { (const char *) 0, (const char *) 0, "tengu" },
    { (const char *) 0, (const char *) 0, "blue jelly" },
    { (const char *) 0, (const char *) 0, "spotted jelly" },
    { (const char *) 0, (const char *) 0, "ochre jelly" },
    { (const char *) 0, (const char *) 0, "kobold" },
    { (const char *) 0, (const char *) 0, "large kobold" },
    { "kobold lord", "kobold lady", "kobold leader" },
    { (const char *) 0, (const char *) 0, "kobold shaman" },
    { (const char *) 0, (const char *) 0, "leprechaun" },
    { (const char *) 0, (const char *) 0, "small mimic" },
    { (const char *) 0, (const char *) 0, "large mimic" },
    { (const char *) 0, (const char *) 0, "giant mimic" },
    { (const char *) 0, (const char *) 0, "wood nymph" },
    { (const char *) 0, (const char *) 0, "water nymph" },
    { (const char *) 0, (const char *) 0, "mountain nymph" },
    { (const char *) 0, (const char *) 0, "goblin" },
    { (const char *) 0, (const char *) 0, "hobgoblin" },
    { (const char *) 0, (const char *) 0, "orc" },
    { (const char *) 0, (const char *) 0, "hill orc" },
    { (const char *) 0, (const char *) 0, "Mordor orc" },
    { (const char *) 0, (const char *) 0, "Uruk-hai" },
    { (const char *) 0, (const char *) 0, "orc shaman" },
    { (const char *) 0, (const char *) 0, "orc-captain" },
    { (const char *) 0, (const char *) 0, "rock piercer" },
    { (const char *) 0, (const char *) 0, "iron piercer" },
    { (const char *) 0, (const char *) 0, "glass piercer" },
    { (const char *) 0, (const char *) 0, "rothe" },
    { (const char *) 0, (const char *) 0, "mumak" },
    { (const char *) 0, (const char *) 0, "leocrotta" },
    { (const char *) 0, (const char *) 0, "wumpus" },
    { (const char *) 0, (const char *) 0, "titanothere" },
    { (const char *) 0, (const char *) 0, "baluchitherium" },
    { (const char *) 0, (const char *) 0, "mastodon" },
    { (const char *) 0, (const char *) 0, "sewer rat" },
    { (const char *) 0, (const char *) 0, "giant rat" },
    { (const char *) 0, (const char *) 0, "rabid rat" },
    { (const char *) 0, (const char *) 0, "wererat" },
    { (const char *) 0, (const char *) 0, "rock mole" },
    { (const char *) 0, (const char *) 0, "woodchuck" },
    { (const char *) 0, (const char *) 0, "cave spider" },
    { (const char *) 0, (const char *) 0, "centipede" },
    { (const char *) 0, (const char *) 0, "giant spider" },
    { (const char *) 0, (const char *) 0, "scorpion" },
    { (const char *) 0, (const char *) 0, "lurker above" },
    { (const char *) 0, (const char *) 0, "trapper" },
    { (const char *) 0, (const char *) 0, "pony" },
    { (const char *) 0, (const char *) 0, "white unicorn" },
    { (const char *) 0, (const char *) 0, "gray unicorn" },
    { (const char *) 0, (const char *) 0, "black unicorn" },
    { (const char *) 0, (const char *) 0, "horse" },
    { (const char *) 0, (const char *) 0, "warhorse" },
    { (const char *) 0, (const char *) 0, "fog cloud" },
    { (const char *) 0, (const char *) 0, "dust vortex" },
    { (const char *) 0, (const char *) 0, "ice vortex" },
    { (const char *) 0, (const char *) 0, "energy vortex" },
    { (const char *) 0, (const char *) 0, "steam vortex" },
    { (const char *) 0, (const char *) 0, "fire vortex" },
    { (const char *) 0, (const char *) 0, "baby long worm" },
    { (const char *) 0, (const char *) 0, "baby purple worm" },
    { (const char *) 0, (const char *) 0, "long worm" },
    { (const char *) 0, (const char *) 0, "purple worm" },
    { (const char *) 0, (const char *) 0, "grid bug" },
    { (const char *) 0, (const char *) 0, "xan" },
    { (const char *) 0, (const char *) 0, "yellow light" },
    { (const char *) 0, (const char *) 0, "black light" },
    { (const char *) 0, (const char *) 0, "zruty" },
    { (const char *) 0, (const char *) 0, "couatl" },
    { (const char *) 0, (const char *) 0, "Aleax" },
    { (const char *) 0, (const char *) 0, "Angel" },
    { (const char *) 0, (const char *) 0, "ki-rin" },
    { (const char *) 0, (const char *) 0, "Archon" },
    { (const char *) 0, (const char *) 0, "bat" },
    { (const char *) 0, (const char *) 0, "giant bat" },
    { (const char *) 0, (const char *) 0, "raven" },
    { (const char *) 0, (const char *) 0, "vampire bat" },
    { (const char *) 0, (const char *) 0, "plains centaur" },
    { (const char *) 0, (const char *) 0, "forest centaur" },
    { (const char *) 0, (const char *) 0, "mountain centaur" },
    { (const char *) 0, (const char *) 0, "baby gray dragon" },
    { (const char *) 0, (const char *) 0, "baby gold dragon" },
    { (const char *) 0, (const char *) 0, "baby silver dragon" },
    { (const char *) 0, (const char *) 0, "baby red dragon" },
    { (const char *) 0, (const char *) 0, "baby white dragon" },
    { (const char *) 0, (const char *) 0, "baby orange dragon" },
    { (const char *) 0, (const char *) 0, "baby black dragon" },
    { (const char *) 0, (const char *) 0, "baby blue dragon" },
    { (const char *) 0, (const char *) 0, "baby green dragon" },
    { (const char *) 0, (const char *) 0, "baby yellow dragon" },
    { (const char *) 0, (const char *) 0, "gray dragon" },
    { (const char *) 0, (const char *) 0, "gold dragon" },
    { (const char *) 0, (const char *) 0, "silver dragon" },
    { (const char *) 0, (const char *) 0, "red dragon" },
    { (const char *) 0, (const char *) 0, "white dragon" },
    { (const char *) 0, (const char *) 0, "orange dragon" },
    { (const char *) 0, (const char *) 0, "black dragon" },
    { (const char *) 0, (const char *) 0, "blue dragon" },
    { (const char *) 0, (const char *) 0, "green dragon" },
    { (const char *) 0, (const char *) 0, "yellow dragon" },
    { (const char *) 0, (const char *) 0, "stalker" },
    { (const char *) 0, (const char *) 0, "air elemental" },
    { (const char *) 0, (const char *) 0, "fire elemental" },
    { (const char *) 0, (const char *) 0, "earth elemental" },
    { (const char *) 0, (const char *) 0, "water elemental" },
    { (const char *) 0, (const char *) 0, "lichen" },
    { (const char *) 0, (const char *) 0, "brown mold" },
    { (const char *) 0, (const char *) 0, "yellow mold" },
    { (const char *) 0, (const char *) 0, "green mold" },
    { (const char *) 0, (const char *) 0, "red mold" },
    { (const char *) 0, (const char *) 0, "shrieker" },
    { (const char *) 0, (const char *) 0, "violet fungus" },
    { (const char *) 0, (const char *) 0, "gnome" },
    { "gnome lord", "gnome lady", "gnome leader" },
    { (const char *) 0, (const char *) 0, "gnomish wizard" },
    { "gnome king", "gnome queen", "gnome ruler" },
    { (const char *) 0, (const char *) 0, "giant" },
    { (const char *) 0, (const char *) 0, "stone giant" },
    { (const char *) 0, (const char *) 0, "hill giant" },
    { (const char *) 0, (const char *) 0, "fire giant" },
    { (const char *) 0, (const char *) 0, "frost giant" },
    { (const char *) 0, (const char *) 0, "ettin" },
    { (const char *) 0, (const char *) 0, "storm giant" },
    { (const char *) 0, (const char *) 0, "titan" },
    { (const char *) 0, (const char *) 0, "minotaur" },
    { (const char *) 0, (const char *) 0, "jabberwock" },
    { (const char *) 0, (const char *) 0, "Keystone Kop" },
    { (const char *) 0, (const char *) 0, "Kop Sergeant" },
    { (const char *) 0, (const char *) 0, "Kop Lieutenant" },
    { (const char *) 0, (const char *) 0, "Kop Kaptain" },
    { (const char *) 0, (const char *) 0, "lich" },
    { (const char *) 0, (const char *) 0, "demilich" },
    { (const char *) 0, (const char *) 0, "master lich" },
    { (const char *) 0, (const char *) 0, "arch-lich" },
    { (const char *) 0, (const char *) 0, "kobold mummy" },
    { (const char *) 0, (const char *) 0, "gnome mummy" },
    { (const char *) 0, (const char *) 0, "orc mummy" },
    { (const char *) 0, (const char *) 0, "dwarf mummy" },
    { (const char *) 0, (const char *) 0, "elf mummy" },
    { (const char *) 0, (const char *) 0, "human mummy" },
    { (const char *) 0, (const char *) 0, "ettin mummy" },
    { (const char *) 0, (const char *) 0, "giant mummy" },
    { (const char *) 0, (const char *) 0, "red naga hatchling" },
    { (const char *) 0, (const char *) 0, "black naga hatchling" },
    { (const char *) 0, (const char *) 0, "golden naga hatchling" },
    { (const char *) 0, (const char *) 0, "guardian naga hatchling" },
    { (const char *) 0, (const char *) 0, "red naga" },
    { (const char *) 0, (const char *) 0, "black naga" },
    { (const char *) 0, (const char *) 0, "golden naga" },
    { (const char *) 0, (const char *) 0, "guardian naga" },
    { (const char *) 0, (const char *) 0, "ogre" },
    { "ogre lord", "ogre lady", "ogre leader" },
    { "ogre king", "ogre queen", "ogre tyrant" },
    { (const char *) 0, (const char *) 0, "gray ooze" },
    { (const char *) 0, (const char *) 0, "brown pudding" },
    { (const char *) 0, (const char *) 0, "green slime" },
    { (const char *) 0, (const char *) 0, "black pudding" },
    { (const char *) 0, (const char *) 0, "quantum mechanic" },
    { (const char *) 0, (const char *) 0, "genetic engineer" },
    { (const char *) 0, (const char *) 0, "rust monster" },
    { (const char *) 0, (const char *) 0, "disenchanter" },
    { (const char *) 0, (const char *) 0, "garter snake" },
    { (const char *) 0, (const char *) 0, "snake" },
    { (const char *) 0, (const char *) 0, "water moccasin" },
    { (const char *) 0, (const char *) 0, "python" },
    { (const char *) 0, (const char *) 0, "pit viper" },
    { (const char *) 0, (const char *) 0, "cobra" },
    { (const char *) 0, (const char *) 0, "troll" },
    { (const char *) 0, (const char *) 0, "ice troll" },
    { (const char *) 0, (const char *) 0, "rock troll" },
    { (const char *) 0, (const char *) 0, "water troll" },
    { (const char *) 0, (const char *) 0, "Olog-hai" },
    { (const char *) 0, (const char *) 0, "umber hulk" },
    { (const char *) 0, (const char *) 0, "vampire" },
    { "vampire lord", "vampire lady", "vampire leader" },
    { (const char *) 0, (const char *) 0, "Vlad the Impaler" },
    { (const char *) 0, (const char *) 0, "barrow wight" },
    { (const char *) 0, (const char *) 0, "wraith" },
    { (const char *) 0, (const char *) 0, "Nazgul" },
    { (const char *) 0, (const char *) 0, "xorn" },
    { (const char *) 0, (const char *) 0, "monkey" },
    { (const char *) 0, (const char *) 0, "ape" },
    { (const char *) 0, (const char *) 0, "owlbear" },
    { (const char *) 0, (const char *) 0, "yeti" },
    { (const char *) 0, (const char *) 0, "carnivorous ape" },
    { (const char *) 0, (const char *) 0, "sasquatch" },
    { (const char *) 0, (const char *) 0, "kobold zombie" },
    { (const char *) 0, (const char *) 0, "gnome zombie" },
    { (const char *) 0, (const char *) 0, "orc zombie" },
    { (const char *) 0, (const char *) 0, "dwarf zombie" },
    { (const char *) 0, (const char *) 0, "elf zombie" },
    { (const char *) 0, (const char *) 0, "human zombie" },
    { (const char *) 0, (const char *) 0, "ettin zombie" },
    { (const char *) 0, (const char *) 0, "ghoul" },
    { (const char *) 0, (const char *) 0, "giant zombie" },
    { (const char *) 0, (const char *) 0, "skeleton" },
    { (const char *) 0, (const char *) 0, "straw golem" },
    { (const char *) 0, (const char *) 0, "paper golem" },
    { (const char *) 0, (const char *) 0, "rope golem" },
    { (const char *) 0, (const char *) 0, "gold golem" },
    { (const char *) 0, (const char *) 0, "leather golem" },
    { (const char *) 0, (const char *) 0, "wood golem" },
    { (const char *) 0, (const char *) 0, "flesh golem" },
    { (const char *) 0, (const char *) 0, "clay golem" },
    { (const char *) 0, (const char *) 0, "stone golem" },
    { (const char *) 0, (const char *) 0, "glass golem" },
    { (const char *) 0, (const char *) 0, "iron golem" },
    { (const char *) 0, (const char *) 0, "human" },
    { (const char *) 0, (const char *) 0, "wererat" },
    { (const char *) 0, (const char *) 0, "werejackal" },
    { (const char *) 0, (const char *) 0, "werewolf" },
    { (const char *) 0, (const char *) 0, "elf" },
    { (const char *) 0, (const char *) 0, "Woodland-elf" },
    { (const char *) 0, (const char *) 0, "Green-elf" },
    { (const char *) 0, (const char *) 0, "Grey-elf" },
    { "elf-lord", "elf-lady", "elf-noble" },
    { "Elvenking", "Elvenqueen", "elven monarch" },
    { (const char *) 0, (const char *) 0, "doppelganger" },
    { (const char *) 0, (const char *) 0, "shopkeeper" },
    { (const char *) 0, (const char *) 0, "guard" },
    { (const char *) 0, (const char *) 0, "prisoner" },
    { (const char *) 0, (const char *) 0, "Oracle" },
    { "priest", "priestess", "aligned cleric" },
    { "high priest", "high priestess", "high cleric" },
    { (const char *) 0, (const char *) 0, "soldier" },
    { (const char *) 0, (const char *) 0, "sergeant" },
    { (const char *) 0, (const char *) 0, "nurse" },
    { (const char *) 0, (const char *) 0, "lieutenant" },
    { (const char *) 0, (const char *) 0, "captain" },
    { (const char *) 0, (const char *) 0, "watchman" },
    { (const char *) 0, (const char *) 0, "watch captain" },
    { (const char *) 0, (const char *) 0, "Medusa" },
    { (const char *) 0, (const char *) 0, "Wizard of Yendor" },
    { (const char *) 0, (const char *) 0, "Croesus" },
    { (const char *) 0, (const char *) 0, "ghost" },
    { (const char *) 0, (const char *) 0, "shade" },
    { (const char *) 0, (const char *) 0, "water demon" },
    { "incubus", "succubus", "amorous demon" },
    { (const char *) 0, (const char *) 0, "horned devil" },
    { (const char *) 0, (const char *) 0, "erinys" },
    { (const char *) 0, (const char *) 0, "barbed devil" },
    { (const char *) 0, (const char *) 0, "marilith" },
    { (const char *) 0, (const char *) 0, "vrock" },
    { (const char *) 0, (const char *) 0, "hezrou" },
    { (const char *) 0, (const char *) 0, "bone devil" },
    { (const char *) 0, (const char *) 0, "ice devil" },
    { (const char *) 0, (const char *) 0, "nalfeshnee" },
    { (const char *) 0, (const char *) 0, "pit fiend" },
    { (const char *) 0, (const char *) 0, "sandestin" },
    { (const char *) 0, (const char *) 0, "balrog" },
    { (const char *) 0, (const char *) 0, "Juiblex" },
    { (const char *) 0, (const char *) 0, "Yeenoghu" },
    { (const char *) 0, (const char *) 0, "Orcus" },
    { (const char *) 0, (const char *) 0, "Geryon" },
    { (const char *) 0, (const char *) 0, "Dispater" },
    { (const char *) 0, (const char *) 0, "Baalzebub" },
    { (const char *) 0, (const char *) 0, "Asmodeus" },
    { (const char *) 0, (const char *) 0, "Demogorgon" },
    { (const char *) 0, (const char *) 0, "Death" },
    { (const char *) 0, (const char *) 0, "Pestilence" },
    { (const char *) 0, (const char *) 0, "Famine" },
    { (const char *) 0, (const char *) 0, "mail daemon" },
    { (const char *) 0, (const char *) 0, "djinni" },
    { (const char *) 0, (const char *) 0, "jellyfish" },
    { (const char *) 0, (const char *) 0, "piranha" },
    { (const char *) 0, (const char *) 0, "shark" },
    { (const char *) 0, (const char *) 0, "giant eel" },
    { (const char *) 0, (const char *) 0, "electric eel" },
    { (const char *) 0, (const char *) 0, "kraken" },
    { (const char *) 0, (const char *) 0, "newt" },
    { (const char *) 0, (const char *) 0, "gecko" },
    { (const char *) 0, (const char *) 0, "iguana" },
    { (const char *) 0, (const char *) 0, "baby crocodile" },
    { (const char *) 0, (const char *) 0, "lizard" },
    { (const char *) 0, (const char *) 0, "chameleon" },
    { (const char *) 0, (const char *) 0, "crocodile" },
    { (const char *) 0, (const char *) 0, "salamander" },
    { (const char *) 0, (const char *) 0, "long worm tail" },
    { (const char *) 0, (const char *) 0, "archeologist" },
    { (const char *) 0, (const char *) 0, "barbarian" },
    { "caveman", "cavewoman", "cave dweller" },
    { (const char *) 0, (const char *) 0, "healer" },
    { (const char *) 0, (const char *) 0, "knight" },
    { (const char *) 0, (const char *) 0, "monk" },
    { "priest", "priestess", "cleric" },
    { (const char *) 0, (const char *) 0, "ranger" },
    { (const char *) 0, (const char *) 0, "rogue" },
    { (const char *) 0, (const char *) 0, "samurai" },
    { (const char *) 0, (const char *) 0, "tourist" },
    { (const char *) 0, (const char *) 0, "valkyrie" },
    { (const char *) 0, (const char *) 0, "wizard" },
    { (const char *) 0, (const char *) 0, "Lord Carnarvon" },
    { (const char *) 0, (const char *) 0, "Pelias" },
    { (const char *) 0, (const char *) 0, "Shaman Karnov" },
    { (const char *) 0, (const char *) 0, "Hippocrates" },
    { (const char *) 0, (const char *) 0, "King Arthur" },
    { (const char *) 0, (const char *) 0, "Grand Master" },
    { (const char *) 0, (const char *) 0, "Arch Priest" },
    { (const char *) 0, (const char *) 0, "Orion" },
    { (const char *) 0, (const char *) 0, "Master of Thieves" },
    { (const char *) 0, (const char *) 0, "Lord Sato" },
    { (const char *) 0, (const char *) 0, "Twoflower" },
    { (const char *) 0, (const char *) 0, "Norn" },
    { (const char *) 0, (const char *) 0, "Neferet the Green" },
    { (const char *) 0, (const char *) 0, "Minion of Huhetotl" },
    { (const char *) 0, (const char *) 0, "Thoth Amon" },
    { (const char *) 0, (const char *) 0, "Chromatic Dragon" },
    { (const char *) 0, (const char *) 0, "Cyclops" },
    { (const char *) 0, (const char *) 0, "Ixoth" },
    { (const char *) 0, (const char *) 0, "Master Kaen" },
    { (const char *) 0, (const char *) 0, "Nalzok" },
    { (const char *) 0, (const char *) 0, "Scorpius" },
    { (const char *) 0, (const char *) 0, "Master Assassin" },
    { (const char *) 0, (const char *) 0, "Ashikaga Takauji" },
    { (const char *) 0, (const char *) 0, "Lord Surtur" },
    { (const char *) 0, (const char *) 0, "Dark One" },
    { (const char *) 0, (const char *) 0, "student" },
    { (const char *) 0, (const char *) 0, "chieftain" },
    { (const char *) 0, (const char *) 0, "neanderthal" },
    { (const char *) 0, (const char *) 0, "attendant" },
    { (const char *) 0, (const char *) 0, "page" },
    { (const char *) 0, (const char *) 0, "abbot" },
    { (const char *) 0, (const char *) 0, "acolyte" },
    { (const char *) 0, (const char *) 0, "hunter" },
    { (const char *) 0, (const char *) 0, "thug" },
    { (const char *) 0, (const char *) 0, "ninja" },
    { (const char *) 0, (const char *) 0, "roshi" },
    { (const char *) 0, (const char *) 0, "guide" },
    { (const char *) 0, (const char *) 0, "warrior" },
    { (const char *) 0, (const char *) 0, "apprentice" },
    { (const char *) 0, (const char *) 0, "" },
};

/*noms_en.c*/
