/* noms_en.c : noms anglais d'origine des objets et monstres, conserves
 * pour les recherches par nom (niveaux Lua, voeux, options). Genere. */

#include "hack.h"

const char *const en_obj_names[NUM_OBJECTS + 1] = {
    "strange object",
    "generic strange",
    "generic weapon",
    "generic armor",
    "generic ring",
    "generic amulet",
    "generic tool",
    "generic food",
    "generic potion",
    "generic scroll",
    "generic spellbook",
    "generic wand",
    "generic coin",
    "generic gem",
    "generic large rock",
    "generic iron ball",
    "generic iron chain",
    "generic venom",
    "arrow",
    "elven arrow",
    "orcish arrow",
    "silver arrow",
    "ya",
    "crossbow bolt",
    "dart",
    "shuriken",
    "boomerang",
    "spear",
    "elven spear",
    "orcish spear",
    "dwarvish spear",
    "silver spear",
    "javelin",
    "trident",
    "dagger",
    "elven dagger",
    "orcish dagger",
    "silver dagger",
    "athame",
    "scalpel",
    "knife",
    "stiletto",
    "worm tooth",
    "crysknife",
    "axe",
    "battle-axe",
    "short sword",
    "elven short sword",
    "orcish short sword",
    "dwarvish short sword",
    "scimitar",
    "silver saber",
    "broadsword",
    "elven broadsword",
    "long sword",
    "two-handed sword",
    "katana",
    "tsurugi",
    "runesword",
    "partisan",
    "ranseur",
    "spetum",
    "glaive",
    "halberd",
    "bardiche",
    "voulge",
    "fauchard",
    "guisarme",
    "bill-guisarme",
    "lucern hammer",
    "bec de corbin",
    "dwarvish mattock",
    "lance",
    "mace",
    "silver mace",
    "morning star",
    "war hammer",
    "club",
    "rubber hose",
    "quarterstaff",
    "aklys",
    "flail",
    "bullwhip",
    "bow",
    "elven bow",
    "orcish bow",
    "yumi",
    "sling",
    "crossbow",
    "elven leather helm",
    "orcish helm",
    "dwarvish iron helm",
    "fedora",
    "cornuthaum",
    "dunce cap",
    "dented pot",
    "helm of brilliance",
    "helmet",
    "helm of caution",
    "helm of opposite alignment",
    "helm of telepathy",
    "gray dragon scale mail",
    "gold dragon scale mail",
    "silver dragon scale mail",
    "red dragon scale mail",
    "white dragon scale mail",
    "orange dragon scale mail",
    "black dragon scale mail",
    "blue dragon scale mail",
    "green dragon scale mail",
    "yellow dragon scale mail",
    "gray dragon scales",
    "gold dragon scales",
    "silver dragon scales",
    "red dragon scales",
    "white dragon scales",
    "orange dragon scales",
    "black dragon scales",
    "blue dragon scales",
    "green dragon scales",
    "yellow dragon scales",
    "plate mail",
    "crystal plate mail",
    "bronze plate mail",
    "splint mail",
    "banded mail",
    "dwarvish mithril-coat",
    "elven mithril-coat",
    "chain mail",
    "orcish chain mail",
    "scale mail",
    "studded leather armor",
    "ring mail",
    "orcish ring mail",
    "leather armor",
    "leather jacket",
    "Hawaiian shirt",
    "T-shirt",
    "mummy wrapping",
    "elven cloak",
    "orcish cloak",
    "dwarvish cloak",
    "oilskin cloak",
    "robe",
    "alchemy smock",
    "leather cloak",
    "cloak of protection",
    "cloak of invisibility",
    "cloak of magic resistance",
    "cloak of displacement",
    "small shield",
    "shield of drain resistance",
    "shield of shock resistance",
    "elven shield",
    "Uruk-hai shield",
    "orcish shield",
    "large shield",
    "dwarvish roundshield",
    "shield of reflection",
    "leather gloves",
    "gauntlets of fumbling",
    "gauntlets of power",
    "gauntlets of dexterity",
    "low boots",
    "iron shoes",
    "high boots",
    "speed boots",
    "water walking boots",
    "jumping boots",
    "elven boots",
    "kicking boots",
    "fumble boots",
    "levitation boots",
    "adornment",
    "gain strength",
    "gain constitution",
    "increase accuracy",
    "increase damage",
    "protection",
    "regeneration",
    "searching",
    "stealth",
    "sustain ability",
    "levitation",
    "hunger",
    "aggravate monster",
    "conflict",
    "warning",
    "poison resistance",
    "fire resistance",
    "cold resistance",
    "shock resistance",
    "free action",
    "slow digestion",
    "teleportation",
    "teleport control",
    "polymorph",
    "polymorph control",
    "invisibility",
    "see invisible",
    "protection from shape changers",
    "amulet of ESP",
    "amulet of life saving",
    "amulet of strangulation",
    "amulet of restful sleep",
    "amulet versus poison",
    "amulet of change",
    "amulet of unchanging",
    "amulet of reflection",
    "amulet of magical breathing",
    "amulet of guarding",
    "amulet of flying",
    "cheap plastic imitation of the Amulet of Yendor",
    "Amulet of Yendor",
    "large box",
    "chest",
    "ice box",
    "sack",
    "oilskin sack",
    "bag of holding",
    "bag of tricks",
    "skeleton key",
    "lock pick",
    "credit card",
    "tallow candle",
    "wax candle",
    "brass lantern",
    "oil lamp",
    "magic lamp",
    "expensive camera",
    "mirror",
    "crystal ball",
    "lenses",
    "blindfold",
    "towel",
    "saddle",
    "leash",
    "stethoscope",
    "tinning kit",
    "tin opener",
    "can of grease",
    "figurine",
    "magic marker",
    "land mine",
    "beartrap",
    "tin whistle",
    "magic whistle",
    "wooden flute",
    "magic flute",
    "tooled horn",
    "frost horn",
    "fire horn",
    "horn of plenty",
    "wooden harp",
    "magic harp",
    "bell",
    "bugle",
    "leather drum",
    "drum of earthquake",
    "pick-axe",
    "grappling hook",
    "unicorn horn",
    "Candelabrum of Invocation",
    "Bell of Opening",
    "tripe ration",
    "corpse",
    "egg",
    "meatball",
    "meat stick",
    "enormous meatball",
    "meat ring",
    "glob of gray ooze",
    "glob of brown pudding",
    "glob of green slime",
    "glob of black pudding",
    "kelp frond",
    "eucalyptus leaf",
    "apple",
    "orange",
    "pear",
    "melon",
    "banana",
    "carrot",
    "sprig of wolfsbane",
    "clove of garlic",
    "slime mold",
    "lump of royal jelly",
    "cream pie",
    "candy bar",
    "fortune cookie",
    "pancake",
    "lembas wafer",
    "cram ration",
    "food ration",
    "K-ration",
    "C-ration",
    "tin",
    "gain ability",
    "restore ability",
    "confusion",
    "blindness",
    "paralysis",
    "speed",
    "levitation",
    "hallucination",
    "invisibility",
    "see invisible",
    "healing",
    "extra healing",
    "gain level",
    "enlightenment",
    "monster detection",
    "object detection",
    "gain energy",
    "sleeping",
    "full healing",
    "polymorph",
    "booze",
    "sickness",
    "fruit juice",
    "acid",
    "oil",
    "water",
    "enchant armor",
    "destroy armor",
    "confuse monster",
    "scare monster",
    "remove curse",
    "enchant weapon",
    "create monster",
    "taming",
    "genocide",
    "light",
    "teleportation",
    "gold detection",
    "food detection",
    "identify",
    "magic mapping",
    "amnesia",
    "fire",
    "earth",
    "punishment",
    "charging",
    "stinking cloud",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "mail",
    "blank paper",
    "dig",
    "magic missile",
    "fireball",
    "cone of cold",
    "sleep",
    "finger of death",
    "light",
    "detect monsters",
    "healing",
    "knock",
    "force bolt",
    "confuse monster",
    "cure blindness",
    "drain life",
    "slow monster",
    "wizard lock",
    "create monster",
    "detect food",
    "cause fear",
    "clairvoyance",
    "cure sickness",
    "charm monster",
    "haste self",
    "detect unseen",
    "levitation",
    "extra healing",
    "restore ability",
    "invisibility",
    "detect treasure",
    "remove curse",
    "magic mapping",
    "identify",
    "turn undead",
    "polymorph",
    "teleport away",
    "create familiar",
    "cancellation",
    "protection",
    "jumping",
    "stone to flesh",
    "chain lightning",
    "blank paper",
    "novel",
    "Book of the Dead",
    "light",
    "secret door detection",
    "enlightenment",
    "create monster",
    "wishing",
    "stasis",
    "nothing",
    "striking",
    "make invisible",
    "slow monster",
    "speed monster",
    "undead turning",
    "polymorph",
    "cancellation",
    "teleportation",
    "opening",
    "locking",
    "probing",
    "digging",
    "magic missile",
    "fire",
    "cold",
    "sleep",
    "death",
    "lightning",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "gold piece",
    "dilithium crystal",
    "diamond",
    "ruby",
    "jacinth",
    "sapphire",
    "black opal",
    "emerald",
    "turquoise",
    "citrine",
    "aquamarine",
    "amber",
    "topaz",
    "jet",
    "opal",
    "chrysoberyl",
    "garnet",
    "amethyst",
    "jasper",
    "fluorite",
    "obsidian",
    "agate",
    "jade",
    "worthless piece of white glass",
    "worthless piece of blue glass",
    "worthless piece of red glass",
    "worthless piece of yellowish brown glass",
    "worthless piece of orange glass",
    "worthless piece of yellow glass",
    "worthless piece of black glass",
    "worthless piece of green glass",
    "worthless piece of violet glass",
    "luckstone",
    "loadstone",
    "touchstone",
    "flint",
    "rock",
    "boulder",
    "statue",
    "heavy iron ball",
    "iron chain",
    "splash of blinding venom",
    "splash of acid venom",
    (const char *) 0,
};

const char *const en_obj_descrs[NUM_OBJECTS + 1] = {
    (const char *) 0,
    "strange",
    "weapon",
    "armor",
    "ring",
    "amulet",
    "tool",
    "food",
    "potion",
    "scroll",
    "spellbook",
    "wand",
    "coin",
    "gem",
    "large rock",
    "iron ball",
    "iron chain",
    "venom",
    (const char *) 0,
    "runed arrow",
    "crude arrow",
    (const char *) 0,
    "bamboo arrow",
    (const char *) 0,
    (const char *) 0,
    "throwing star",
    (const char *) 0,
    (const char *) 0,
    "runed spear",
    "crude spear",
    "stout spear",
    (const char *) 0,
    "throwing spear",
    (const char *) 0,
    (const char *) 0,
    "runed dagger",
    "crude dagger",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "double-headed axe",
    (const char *) 0,
    "runed short sword",
    "crude short sword",
    "broad short sword",
    "curved sword",
    (const char *) 0,
    (const char *) 0,
    "runed broadsword",
    (const char *) 0,
    (const char *) 0,
    "samurai sword",
    "long samurai sword",
    "runed broadsword",
    "vulgar polearm",
    "hilted polearm",
    "forked polearm",
    "single-edged polearm",
    "angled poleaxe",
    "long poleaxe",
    "pole cleaver",
    "pole sickle",
    "pruning hook",
    "hooked polearm",
    "pronged polearm",
    "beaked polearm",
    "broad pick",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "staff",
    "thonged club",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "runed bow",
    "crude bow",
    "long bow",
    (const char *) 0,
    (const char *) 0,
    "leather hat",
    "iron skull cap",
    "hard hat",
    (const char *) 0,
    "conical hat",
    "conical hat",
    (const char *) 0,
    "crystal helmet",
    "plumed helmet",
    "etched helmet",
    "crested helmet",
    "visored helmet",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "crude chain mail",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "crude ring mail",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "faded pall",
    "coarse mantelet",
    "hooded cloak",
    "slippery cloak",
    (const char *) 0,
    "apron",
    (const char *) 0,
    "tattered cape",
    "opera cloak",
    "ornamental cope",
    "piece of cloth",
    "wooden shield",
    "wooden shield",
    "wooden shield",
    "blue and green shield",
    "white-handed shield",
    "red-eyed shield",
    (const char *) 0,
    "large round shield",
    "polished silver shield",
    "old gloves",
    "padded gloves",
    "riding gloves",
    "fencing gloves",
    "walking shoes",
    "hard shoes",
    "jackboots",
    "combat boots",
    "jungle boots",
    "hiking boots",
    "mud boots",
    "buckled boots",
    "riding boots",
    "snow boots",
    "wooden",
    "granite",
    "opal",
    "clay",
    "coral",
    "black onyx",
    "moonstone",
    "tiger eye",
    "jade",
    "bronze",
    "agate",
    "topaz",
    "sapphire",
    "ruby",
    "diamond",
    "pearl",
    "iron",
    "brass",
    "copper",
    "twisted",
    "steel",
    "silver",
    "gold",
    "ivory",
    "emerald",
    "wire",
    "engagement",
    "shiny",
    "circular",
    "spherical",
    "oval",
    "triangular",
    "pyramidal",
    "square",
    "concave",
    "hexagonal",
    "octagonal",
    "perforated",
    "cubical",
    "Amulet of Yendor",
    "Amulet of Yendor",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "bag",
    "bag",
    "bag",
    "bag",
    "key",
    (const char *) 0,
    (const char *) 0,
    "candle",
    "candle",
    (const char *) 0,
    "lamp",
    "lamp",
    (const char *) 0,
    "looking glass",
    "glass orb",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "whistle",
    "whistle",
    "flute",
    "flute",
    "horn",
    "horn",
    "horn",
    "horn",
    "harp",
    "harp",
    (const char *) 0,
    (const char *) 0,
    "drum",
    "drum",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "candelabrum",
    "silver bell",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "ruby",
    "pink",
    "orange",
    "yellow",
    "emerald",
    "dark green",
    "cyan",
    "sky blue",
    "brilliant blue",
    "magenta",
    "purple-red",
    "puce",
    "milky",
    "swirly",
    "bubbly",
    "smoky",
    "cloudy",
    "effervescent",
    "black",
    "golden",
    "brown",
    "fizzy",
    "dark",
    "white",
    "murky",
    "clear",
    "ZELGO MER",
    "JUYED AWK YACC",
    "NR 9",
    "XIXAXA XOXAXA XUXAXA",
    "PRATYAVAYAH",
    "DAIYEN FOOELS",
    "LEP GEX VEN ZEA",
    "PRIRUTSENIE",
    "ELBIB YLOH",
    "VERR YED HORRE",
    "VENZAR BORGAVVE",
    "THARR",
    "YUM YUM",
    "KERNOD WEL",
    "ELAM EBOW",
    "DUAM XNAHT",
    "ANDOVA BEGARIN",
    "KIRJE",
    "VE FORBRYDERNE",
    "HACKEM MUCHE",
    "VELOX NEB",
    "FOOBIE BLETCH",
    "TEMOV",
    "GARVEN DEH",
    "READ ME",
    "ETAOIN SHRDLU",
    "LOREM IPSUM",
    "FNORD",
    "KO BATE",
    "ABRA KA DABRA",
    "ASHPD SODALG",
    "ZLORFIK",
    "GNIK SISI VLE",
    "HAPAX LEGOMENON",
    "EIRIS SAZUN IDISI",
    "PHOL ENDE WODAN",
    "GHOTI",
    "MAPIRO MAHAMA DIROMAT",
    "VAS CORP BET MANI",
    "XOR OTA",
    "STRC PRST SKRZ KRK",
    "stamped",
    "unlabeled",
    "parchment",
    "vellum",
    "ragged",
    "dog eared",
    "mottled",
    "stained",
    "cloth",
    "leathery",
    "white",
    "pink",
    "red",
    "orange",
    "yellow",
    "velvet",
    "light green",
    "dark green",
    "turquoise",
    "cyan",
    "light blue",
    "dark blue",
    "indigo",
    "magenta",
    "purple",
    "violet",
    "tan",
    "plaid",
    "light brown",
    "dark brown",
    "gray",
    "wrinkled",
    "dusty",
    "bronze",
    "copper",
    "silver",
    "gold",
    "glittering",
    "shining",
    "dull",
    "thin",
    "thick",
    "checkered",
    "plain",
    "paperback",
    "papyrus",
    "glass",
    "balsa",
    "crystal",
    "maple",
    "pine",
    "redwood",
    "oak",
    "ebony",
    "marble",
    "tin",
    "brass",
    "copper",
    "silver",
    "platinum",
    "iridium",
    "zinc",
    "aluminum",
    "uranium",
    "iron",
    "steel",
    "hexagonal",
    "short",
    "runed",
    "long",
    "curved",
    "forked",
    "spiked",
    "jeweled",
    (const char *) 0,
    "white",
    "white",
    "red",
    "orange",
    "blue",
    "black",
    "green",
    "green",
    "yellow",
    "green",
    "yellowish brown",
    "yellowish brown",
    "black",
    "white",
    "yellow",
    "red",
    "violet",
    "red",
    "violet",
    "black",
    "orange",
    "green",
    "white",
    "blue",
    "red",
    "yellowish brown",
    "orange",
    "yellow",
    "black",
    "green",
    "violet",
    "gray",
    "gray",
    "gray",
    "gray",
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    (const char *) 0,
    "splash of venom",
    "splash of venom",
    (const char *) 0,
};

const char *const en_mon_names[NUMMONS + 1][NUM_MGENDERS] = {
    { (const char *) 0, (const char *) 0, "giant ant" },
    { (const char *) 0, (const char *) 0, "killer bee" },
    { (const char *) 0, (const char *) 0, "soldier ant" },
    { (const char *) 0, (const char *) 0, "fire ant" },
    { (const char *) 0, (const char *) 0, "giant beetle" },
    { (const char *) 0, (const char *) 0, "queen bee" },
    { (const char *) 0, (const char *) 0, "acid blob" },
    { (const char *) 0, (const char *) 0, "quivering blob" },
    { (const char *) 0, (const char *) 0, "gelatinous cube" },
    { (const char *) 0, (const char *) 0, "chickatrice" },
    { (const char *) 0, (const char *) 0, "cockatrice" },
    { (const char *) 0, (const char *) 0, "pyrolisk" },
    { (const char *) 0, (const char *) 0, "jackal" },
    { (const char *) 0, (const char *) 0, "fox" },
    { (const char *) 0, (const char *) 0, "coyote" },
    { (const char *) 0, (const char *) 0, "werejackal" },
    { (const char *) 0, (const char *) 0, "little dog" },
    { (const char *) 0, (const char *) 0, "dingo" },
    { (const char *) 0, (const char *) 0, "dog" },
    { (const char *) 0, (const char *) 0, "large dog" },
    { (const char *) 0, (const char *) 0, "wolf" },
    { (const char *) 0, (const char *) 0, "werewolf" },
    { (const char *) 0, (const char *) 0, "winter wolf cub" },
    { (const char *) 0, (const char *) 0, "warg" },
    { (const char *) 0, (const char *) 0, "winter wolf" },
    { (const char *) 0, (const char *) 0, "hell hound pup" },
    { (const char *) 0, (const char *) 0, "hell hound" },
    { (const char *) 0, (const char *) 0, "gas spore" },
    { (const char *) 0, (const char *) 0, "floating eye" },
    { (const char *) 0, (const char *) 0, "freezing sphere" },
    { (const char *) 0, (const char *) 0, "flaming sphere" },
    { (const char *) 0, (const char *) 0, "shocking sphere" },
    { (const char *) 0, (const char *) 0, "kitten" },
    { (const char *) 0, (const char *) 0, "housecat" },
    { (const char *) 0, (const char *) 0, "jaguar" },
    { (const char *) 0, (const char *) 0, "lynx" },
    { (const char *) 0, (const char *) 0, "panther" },
    { (const char *) 0, (const char *) 0, "large cat" },
    { (const char *) 0, (const char *) 0, "tiger" },
    { (const char *) 0, (const char *) 0, "displacer beast" },
    { (const char *) 0, (const char *) 0, "gremlin" },
    { (const char *) 0, (const char *) 0, "gargoyle" },
    { (const char *) 0, (const char *) 0, "winged gargoyle" },
    { (const char *) 0, (const char *) 0, "hobbit" },
    { (const char *) 0, (const char *) 0, "dwarf" },
    { (const char *) 0, (const char *) 0, "bugbear" },
    { "dwarf lord", "dwarf lady", "dwarf leader" },
    { "dwarf king", "dwarf queen", "dwarf ruler" },
    { (const char *) 0, (const char *) 0, "mind flayer" },
    { (const char *) 0, (const char *) 0, "master mind flayer" },
    { (const char *) 0, (const char *) 0, "manes" },
    { (const char *) 0, (const char *) 0, "homunculus" },
    { (const char *) 0, (const char *) 0, "imp" },
    { (const char *) 0, (const char *) 0, "lemure" },
    { (const char *) 0, (const char *) 0, "quasit" },
    { (const char *) 0, (const char *) 0, "tengu" },
    { (const char *) 0, (const char *) 0, "blue jelly" },
    { (const char *) 0, (const char *) 0, "spotted jelly" },
    { (const char *) 0, (const char *) 0, "ochre jelly" },
    { (const char *) 0, (const char *) 0, "kobold" },
    { (const char *) 0, (const char *) 0, "large kobold" },
    { "kobold lord", "kobold lady", "kobold leader" },
    { (const char *) 0, (const char *) 0, "kobold shaman" },
    { (const char *) 0, (const char *) 0, "leprechaun" },
    { (const char *) 0, (const char *) 0, "small mimic" },
    { (const char *) 0, (const char *) 0, "large mimic" },
    { (const char *) 0, (const char *) 0, "giant mimic" },
    { (const char *) 0, (const char *) 0, "wood nymph" },
    { (const char *) 0, (const char *) 0, "water nymph" },
    { (const char *) 0, (const char *) 0, "mountain nymph" },
    { (const char *) 0, (const char *) 0, "goblin" },
    { (const char *) 0, (const char *) 0, "hobgoblin" },
    { (const char *) 0, (const char *) 0, "orc" },
    { (const char *) 0, (const char *) 0, "hill orc" },
    { (const char *) 0, (const char *) 0, "Mordor orc" },
    { (const char *) 0, (const char *) 0, "Uruk-hai" },
    { (const char *) 0, (const char *) 0, "orc shaman" },
    { (const char *) 0, (const char *) 0, "orc-captain" },
    { (const char *) 0, (const char *) 0, "rock piercer" },
    { (const char *) 0, (const char *) 0, "iron piercer" },
    { (const char *) 0, (const char *) 0, "glass piercer" },
    { (const char *) 0, (const char *) 0, "rothe" },
    { (const char *) 0, (const char *) 0, "mumak" },
    { (const char *) 0, (const char *) 0, "leocrotta" },
    { (const char *) 0, (const char *) 0, "wumpus" },
    { (const char *) 0, (const char *) 0, "titanothere" },
    { (const char *) 0, (const char *) 0, "baluchitherium" },
    { (const char *) 0, (const char *) 0, "mastodon" },
    { (const char *) 0, (const char *) 0, "sewer rat" },
    { (const char *) 0, (const char *) 0, "giant rat" },
    { (const char *) 0, (const char *) 0, "rabid rat" },
    { (const char *) 0, (const char *) 0, "wererat" },
    { (const char *) 0, (const char *) 0, "rock mole" },
    { (const char *) 0, (const char *) 0, "woodchuck" },
    { (const char *) 0, (const char *) 0, "cave spider" },
    { (const char *) 0, (const char *) 0, "centipede" },
    { (const char *) 0, (const char *) 0, "giant spider" },
    { (const char *) 0, (const char *) 0, "scorpion" },
    { (const char *) 0, (const char *) 0, "lurker above" },
    { (const char *) 0, (const char *) 0, "trapper" },
    { (const char *) 0, (const char *) 0, "pony" },
    { (const char *) 0, (const char *) 0, "white unicorn" },
    { (const char *) 0, (const char *) 0, "gray unicorn" },
    { (const char *) 0, (const char *) 0, "black unicorn" },
    { (const char *) 0, (const char *) 0, "horse" },
    { (const char *) 0, (const char *) 0, "warhorse" },
    { (const char *) 0, (const char *) 0, "fog cloud" },
    { (const char *) 0, (const char *) 0, "dust vortex" },
    { (const char *) 0, (const char *) 0, "ice vortex" },
    { (const char *) 0, (const char *) 0, "energy vortex" },
    { (const char *) 0, (const char *) 0, "steam vortex" },
    { (const char *) 0, (const char *) 0, "fire vortex" },
    { (const char *) 0, (const char *) 0, "baby long worm" },
    { (const char *) 0, (const char *) 0, "baby purple worm" },
    { (const char *) 0, (const char *) 0, "long worm" },
    { (const char *) 0, (const char *) 0, "purple worm" },
    { (const char *) 0, (const char *) 0, "grid bug" },
    { (const char *) 0, (const char *) 0, "xan" },
    { (const char *) 0, (const char *) 0, "yellow light" },
    { (const char *) 0, (const char *) 0, "black light" },
    { (const char *) 0, (const char *) 0, "zruty" },
    { (const char *) 0, (const char *) 0, "couatl" },
    { (const char *) 0, (const char *) 0, "Aleax" },
    { (const char *) 0, (const char *) 0, "Angel" },
    { (const char *) 0, (const char *) 0, "ki-rin" },
    { (const char *) 0, (const char *) 0, "Archon" },
    { (const char *) 0, (const char *) 0, "bat" },
    { (const char *) 0, (const char *) 0, "giant bat" },
    { (const char *) 0, (const char *) 0, "raven" },
    { (const char *) 0, (const char *) 0, "vampire bat" },
    { (const char *) 0, (const char *) 0, "plains centaur" },
    { (const char *) 0, (const char *) 0, "forest centaur" },
    { (const char *) 0, (const char *) 0, "mountain centaur" },
    { (const char *) 0, (const char *) 0, "baby gray dragon" },
    { (const char *) 0, (const char *) 0, "baby gold dragon" },
    { (const char *) 0, (const char *) 0, "baby silver dragon" },
    { (const char *) 0, (const char *) 0, "baby red dragon" },
    { (const char *) 0, (const char *) 0, "baby white dragon" },
    { (const char *) 0, (const char *) 0, "baby orange dragon" },
    { (const char *) 0, (const char *) 0, "baby black dragon" },
    { (const char *) 0, (const char *) 0, "baby blue dragon" },
    { (const char *) 0, (const char *) 0, "baby green dragon" },
    { (const char *) 0, (const char *) 0, "baby yellow dragon" },
    { (const char *) 0, (const char *) 0, "gray dragon" },
    { (const char *) 0, (const char *) 0, "gold dragon" },
    { (const char *) 0, (const char *) 0, "silver dragon" },
    { (const char *) 0, (const char *) 0, "red dragon" },
    { (const char *) 0, (const char *) 0, "white dragon" },
    { (const char *) 0, (const char *) 0, "orange dragon" },
    { (const char *) 0, (const char *) 0, "black dragon" },
    { (const char *) 0, (const char *) 0, "blue dragon" },
    { (const char *) 0, (const char *) 0, "green dragon" },
    { (const char *) 0, (const char *) 0, "yellow dragon" },
    { (const char *) 0, (const char *) 0, "stalker" },
    { (const char *) 0, (const char *) 0, "air elemental" },
    { (const char *) 0, (const char *) 0, "fire elemental" },
    { (const char *) 0, (const char *) 0, "earth elemental" },
    { (const char *) 0, (const char *) 0, "water elemental" },
    { (const char *) 0, (const char *) 0, "lichen" },
    { (const char *) 0, (const char *) 0, "brown mold" },
    { (const char *) 0, (const char *) 0, "yellow mold" },
    { (const char *) 0, (const char *) 0, "green mold" },
    { (const char *) 0, (const char *) 0, "red mold" },
    { (const char *) 0, (const char *) 0, "shrieker" },
    { (const char *) 0, (const char *) 0, "violet fungus" },
    { (const char *) 0, (const char *) 0, "gnome" },
    { "gnome lord", "gnome lady", "gnome leader" },
    { (const char *) 0, (const char *) 0, "gnomish wizard" },
    { "gnome king", "gnome queen", "gnome ruler" },
    { (const char *) 0, (const char *) 0, "giant" },
    { (const char *) 0, (const char *) 0, "stone giant" },
    { (const char *) 0, (const char *) 0, "hill giant" },
    { (const char *) 0, (const char *) 0, "fire giant" },
    { (const char *) 0, (const char *) 0, "frost giant" },
    { (const char *) 0, (const char *) 0, "ettin" },
    { (const char *) 0, (const char *) 0, "storm giant" },
    { (const char *) 0, (const char *) 0, "titan" },
    { (const char *) 0, (const char *) 0, "minotaur" },
    { (const char *) 0, (const char *) 0, "jabberwock" },
    { (const char *) 0, (const char *) 0, "Keystone Kop" },
    { (const char *) 0, (const char *) 0, "Kop Sergeant" },
    { (const char *) 0, (const char *) 0, "Kop Lieutenant" },
    { (const char *) 0, (const char *) 0, "Kop Kaptain" },
    { (const char *) 0, (const char *) 0, "lich" },
    { (const char *) 0, (const char *) 0, "demilich" },
    { (const char *) 0, (const char *) 0, "master lich" },
    { (const char *) 0, (const char *) 0, "arch-lich" },
    { (const char *) 0, (const char *) 0, "kobold mummy" },
    { (const char *) 0, (const char *) 0, "gnome mummy" },
    { (const char *) 0, (const char *) 0, "orc mummy" },
    { (const char *) 0, (const char *) 0, "dwarf mummy" },
    { (const char *) 0, (const char *) 0, "elf mummy" },
    { (const char *) 0, (const char *) 0, "human mummy" },
    { (const char *) 0, (const char *) 0, "ettin mummy" },
    { (const char *) 0, (const char *) 0, "giant mummy" },
    { (const char *) 0, (const char *) 0, "red naga hatchling" },
    { (const char *) 0, (const char *) 0, "black naga hatchling" },
    { (const char *) 0, (const char *) 0, "golden naga hatchling" },
    { (const char *) 0, (const char *) 0, "guardian naga hatchling" },
    { (const char *) 0, (const char *) 0, "red naga" },
    { (const char *) 0, (const char *) 0, "black naga" },
    { (const char *) 0, (const char *) 0, "golden naga" },
    { (const char *) 0, (const char *) 0, "guardian naga" },
    { (const char *) 0, (const char *) 0, "ogre" },
    { "ogre lord", "ogre lady", "ogre leader" },
    { "ogre king", "ogre queen", "ogre tyrant" },
    { (const char *) 0, (const char *) 0, "gray ooze" },
    { (const char *) 0, (const char *) 0, "brown pudding" },
    { (const char *) 0, (const char *) 0, "green slime" },
    { (const char *) 0, (const char *) 0, "black pudding" },
    { (const char *) 0, (const char *) 0, "quantum mechanic" },
    { (const char *) 0, (const char *) 0, "genetic engineer" },
    { (const char *) 0, (const char *) 0, "rust monster" },
    { (const char *) 0, (const char *) 0, "disenchanter" },
    { (const char *) 0, (const char *) 0, "garter snake" },
    { (const char *) 0, (const char *) 0, "snake" },
    { (const char *) 0, (const char *) 0, "water moccasin" },
    { (const char *) 0, (const char *) 0, "python" },
    { (const char *) 0, (const char *) 0, "pit viper" },
    { (const char *) 0, (const char *) 0, "cobra" },
    { (const char *) 0, (const char *) 0, "troll" },
    { (const char *) 0, (const char *) 0, "ice troll" },
    { (const char *) 0, (const char *) 0, "rock troll" },
    { (const char *) 0, (const char *) 0, "water troll" },
    { (const char *) 0, (const char *) 0, "Olog-hai" },
    { (const char *) 0, (const char *) 0, "umber hulk" },
    { (const char *) 0, (const char *) 0, "vampire" },
    { "vampire lord", "vampire lady", "vampire leader" },
    { (const char *) 0, (const char *) 0, "Vlad the Impaler" },
    { (const char *) 0, (const char *) 0, "barrow wight" },
    { (const char *) 0, (const char *) 0, "wraith" },
    { (const char *) 0, (const char *) 0, "Nazgul" },
    { (const char *) 0, (const char *) 0, "xorn" },
    { (const char *) 0, (const char *) 0, "monkey" },
    { (const char *) 0, (const char *) 0, "ape" },
    { (const char *) 0, (const char *) 0, "owlbear" },
    { (const char *) 0, (const char *) 0, "yeti" },
    { (const char *) 0, (const char *) 0, "carnivorous ape" },
    { (const char *) 0, (const char *) 0, "sasquatch" },
    { (const char *) 0, (const char *) 0, "kobold zombie" },
    { (const char *) 0, (const char *) 0, "gnome zombie" },
    { (const char *) 0, (const char *) 0, "orc zombie" },
    { (const char *) 0, (const char *) 0, "dwarf zombie" },
    { (const char *) 0, (const char *) 0, "elf zombie" },
    { (const char *) 0, (const char *) 0, "human zombie" },
    { (const char *) 0, (const char *) 0, "ettin zombie" },
    { (const char *) 0, (const char *) 0, "ghoul" },
    { (const char *) 0, (const char *) 0, "giant zombie" },
    { (const char *) 0, (const char *) 0, "skeleton" },
    { (const char *) 0, (const char *) 0, "straw golem" },
    { (const char *) 0, (const char *) 0, "paper golem" },
    { (const char *) 0, (const char *) 0, "rope golem" },
    { (const char *) 0, (const char *) 0, "gold golem" },
    { (const char *) 0, (const char *) 0, "leather golem" },
    { (const char *) 0, (const char *) 0, "wood golem" },
    { (const char *) 0, (const char *) 0, "flesh golem" },
    { (const char *) 0, (const char *) 0, "clay golem" },
    { (const char *) 0, (const char *) 0, "stone golem" },
    { (const char *) 0, (const char *) 0, "glass golem" },
    { (const char *) 0, (const char *) 0, "iron golem" },
    { (const char *) 0, (const char *) 0, "human" },
    { (const char *) 0, (const char *) 0, "wererat" },
    { (const char *) 0, (const char *) 0, "werejackal" },
    { (const char *) 0, (const char *) 0, "werewolf" },
    { (const char *) 0, (const char *) 0, "elf" },
    { (const char *) 0, (const char *) 0, "Woodland-elf" },
    { (const char *) 0, (const char *) 0, "Green-elf" },
    { (const char *) 0, (const char *) 0, "Grey-elf" },
    { "elf-lord", "elf-lady", "elf-noble" },
    { "Elvenking", "Elvenqueen", "elven monarch" },
    { (const char *) 0, (const char *) 0, "doppelganger" },
    { (const char *) 0, (const char *) 0, "shopkeeper" },
    { (const char *) 0, (const char *) 0, "guard" },
    { (const char *) 0, (const char *) 0, "prisoner" },
    { (const char *) 0, (const char *) 0, "Oracle" },
    { "priest", "priestess", "aligned cleric" },
    { "high priest", "high priestess", "high cleric" },
    { (const char *) 0, (const char *) 0, "soldier" },
    { (const char *) 0, (const char *) 0, "sergeant" },
    { (const char *) 0, (const char *) 0, "nurse" },
    { (const char *) 0, (const char *) 0, "lieutenant" },
    { (const char *) 0, (const char *) 0, "captain" },
    { (const char *) 0, (const char *) 0, "watchman" },
    { (const char *) 0, (const char *) 0, "watch captain" },
    { (const char *) 0, (const char *) 0, "Medusa" },
    { (const char *) 0, (const char *) 0, "Wizard of Yendor" },
    { (const char *) 0, (const char *) 0, "Croesus" },
    { (const char *) 0, (const char *) 0, "ghost" },
    { (const char *) 0, (const char *) 0, "shade" },
    { (const char *) 0, (const char *) 0, "water demon" },
    { "incubus", "succubus", "amorous demon" },
    { (const char *) 0, (const char *) 0, "horned devil" },
    { (const char *) 0, (const char *) 0, "erinys" },
    { (const char *) 0, (const char *) 0, "barbed devil" },
    { (const char *) 0, (const char *) 0, "marilith" },
    { (const char *) 0, (const char *) 0, "vrock" },
    { (const char *) 0, (const char *) 0, "hezrou" },
    { (const char *) 0, (const char *) 0, "bone devil" },
    { (const char *) 0, (const char *) 0, "ice devil" },
    { (const char *) 0, (const char *) 0, "nalfeshnee" },
    { (const char *) 0, (const char *) 0, "pit fiend" },
    { (const char *) 0, (const char *) 0, "sandestin" },
    { (const char *) 0, (const char *) 0, "balrog" },
    { (const char *) 0, (const char *) 0, "Juiblex" },
    { (const char *) 0, (const char *) 0, "Yeenoghu" },
    { (const char *) 0, (const char *) 0, "Orcus" },
    { (const char *) 0, (const char *) 0, "Geryon" },
    { (const char *) 0, (const char *) 0, "Dispater" },
    { (const char *) 0, (const char *) 0, "Baalzebub" },
    { (const char *) 0, (const char *) 0, "Asmodeus" },
    { (const char *) 0, (const char *) 0, "Demogorgon" },
    { (const char *) 0, (const char *) 0, "Death" },
    { (const char *) 0, (const char *) 0, "Pestilence" },
    { (const char *) 0, (const char *) 0, "Famine" },
    { (const char *) 0, (const char *) 0, "mail daemon" },
    { (const char *) 0, (const char *) 0, "djinni" },
    { (const char *) 0, (const char *) 0, "jellyfish" },
    { (const char *) 0, (const char *) 0, "piranha" },
    { (const char *) 0, (const char *) 0, "shark" },
    { (const char *) 0, (const char *) 0, "giant eel" },
    { (const char *) 0, (const char *) 0, "electric eel" },
    { (const char *) 0, (const char *) 0, "kraken" },
    { (const char *) 0, (const char *) 0, "newt" },
    { (const char *) 0, (const char *) 0, "gecko" },
    { (const char *) 0, (const char *) 0, "iguana" },
    { (const char *) 0, (const char *) 0, "baby crocodile" },
    { (const char *) 0, (const char *) 0, "lizard" },
    { (const char *) 0, (const char *) 0, "chameleon" },
    { (const char *) 0, (const char *) 0, "crocodile" },
    { (const char *) 0, (const char *) 0, "salamander" },
    { (const char *) 0, (const char *) 0, "long worm tail" },
    { (const char *) 0, (const char *) 0, "archeologist" },
    { (const char *) 0, (const char *) 0, "barbarian" },
    { "caveman", "cavewoman", "cave dweller" },
    { (const char *) 0, (const char *) 0, "healer" },
    { (const char *) 0, (const char *) 0, "knight" },
    { (const char *) 0, (const char *) 0, "monk" },
    { "priest", "priestess", "cleric" },
    { (const char *) 0, (const char *) 0, "ranger" },
    { (const char *) 0, (const char *) 0, "rogue" },
    { (const char *) 0, (const char *) 0, "samurai" },
    { (const char *) 0, (const char *) 0, "tourist" },
    { (const char *) 0, (const char *) 0, "valkyrie" },
    { (const char *) 0, (const char *) 0, "wizard" },
    { (const char *) 0, (const char *) 0, "Lord Carnarvon" },
    { (const char *) 0, (const char *) 0, "Pelias" },
    { (const char *) 0, (const char *) 0, "Shaman Karnov" },
    { (const char *) 0, (const char *) 0, "Hippocrates" },
    { (const char *) 0, (const char *) 0, "King Arthur" },
    { (const char *) 0, (const char *) 0, "Grand Master" },
    { (const char *) 0, (const char *) 0, "Arch Priest" },
    { (const char *) 0, (const char *) 0, "Orion" },
    { (const char *) 0, (const char *) 0, "Master of Thieves" },
    { (const char *) 0, (const char *) 0, "Lord Sato" },
    { (const char *) 0, (const char *) 0, "Twoflower" },
    { (const char *) 0, (const char *) 0, "Norn" },
    { (const char *) 0, (const char *) 0, "Neferet the Green" },
    { (const char *) 0, (const char *) 0, "Minion of Huhetotl" },
    { (const char *) 0, (const char *) 0, "Thoth Amon" },
    { (const char *) 0, (const char *) 0, "Chromatic Dragon" },
    { (const char *) 0, (const char *) 0, "Cyclops" },
    { (const char *) 0, (const char *) 0, "Ixoth" },
    { (const char *) 0, (const char *) 0, "Master Kaen" },
    { (const char *) 0, (const char *) 0, "Nalzok" },
    { (const char *) 0, (const char *) 0, "Scorpius" },
    { (const char *) 0, (const char *) 0, "Master Assassin" },
    { (const char *) 0, (const char *) 0, "Ashikaga Takauji" },
    { (const char *) 0, (const char *) 0, "Lord Surtur" },
    { (const char *) 0, (const char *) 0, "Dark One" },
    { (const char *) 0, (const char *) 0, "student" },
    { (const char *) 0, (const char *) 0, "chieftain" },
    { (const char *) 0, (const char *) 0, "neanderthal" },
    { (const char *) 0, (const char *) 0, "attendant" },
    { (const char *) 0, (const char *) 0, "page" },
    { (const char *) 0, (const char *) 0, "abbot" },
    { (const char *) 0, (const char *) 0, "acolyte" },
    { (const char *) 0, (const char *) 0, "hunter" },
    { (const char *) 0, (const char *) 0, "thug" },
    { (const char *) 0, (const char *) 0, "ninja" },
    { (const char *) 0, (const char *) 0, "roshi" },
    { (const char *) 0, (const char *) 0, "guide" },
    { (const char *) 0, (const char *) 0, "warrior" },
    { (const char *) 0, (const char *) 0, "apprentice" },
    { (const char *) 0, (const char *) 0, "" },
};

const char *const en_defsym_expl[MAXPCHARS + 1] = {
    "stone",
    "wall",
    "wall",
    "wall",
    "wall",
    "wall",
    "wall",
    "wall",
    "wall",
    "wall",
    "wall",
    "wall",
    "doorway",
    "open door",
    "open door",
    "closed door",
    "closed door",
    "iron bars",
    "tree",
    "floor of a room",
    "dark part of a room",
    "engraving",
    "corridor",
    "lit corridor",
    "engraving",
    "staircase up",
    "staircase down",
    "ladder up",
    "ladder down",
    "branch staircase up",
    "branch staircase down",
    "branch ladder up",
    "branch ladder down",
    "altar",
    "grave",
    "opulent throne",
    "sink",
    "fountain",
    "water",
    "ice",
    "molten lava",
    "wall of lava",
    "lowered drawbridge",
    "lowered drawbridge",
    "raised drawbridge",
    "raised drawbridge",
    "air",
    "cloud",
    "water",
    "arrow trap",
    "dart trap",
    "falling rock trap",
    "squeaky board",
    "bear trap",
    "land mine",
    "rolling boulder trap",
    "sleeping gas trap",
    "rust trap",
    "fire trap",
    "pit",
    "spiked pit",
    "hole",
    "trap door",
    "teleportation trap",
    "level teleporter",
    "magic portal",
    "web",
    "statue trap",
    "magic trap",
    "anti-magic field",
    "polymorph trap",
    "vibrating square",
    "trapped door",
    "trapped chest",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "poison cloud",
    "valid position",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    (const char *) 0
};

/*noms_en.c*/
